services:
  api:
    build:
      context: ../
    container_name: catalog_api
    env_file:
      - ../.env
    command: ./infra/commands/api.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery

  db:
    image: postgres:16
    container_name: catalog_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build:
      context: ../
    container_name: celery
    env_file:
      - ../.env
    command: [ "./infra/commands/celery.sh", "celery" ]
    depends_on:
      - redis

  beat:
    build:
      context: ../
    container_name: celery_beat
    env_file:
      - ../.env
    command: [ "./infra/commands/celery.sh", "beat" ]
    depends_on:
      - celery


  flower:
    build:
      context: ../
    container_name: flower
    env_file:
      - ../.env
    command: [ "./infra/commands/celery.sh", "flower" ]
    ports:
      - "5555:5555"
    depends_on:
      - celery

  redis:
    image: redis:7.2.5
    container_name: redis


volumes:
  postgres_data: